export const cremasDucha = [   

    {
        id: 17,
        nombre: "Crema de Ducha Jazmin Casis",
        url: "crema_de_ducha_extra_suave_jazmin_casis",
        descripcion: 'La Crema de Ducha Extra Suave de Jazmín Casis de Le Petit Olivier con extractos botánicos naturales.Combina los beneficios de un gel de ducha y una crema hidratante, limpiando e hidratando la piel suavemente  mientras libera un perfume con notas dulces y florales. Una crema de ducha limpia la piel como un gel de ducha convencional, pero también contiene ingredientes hidratantes. Ideal para pieles secas o sensibles.',
        imagen: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-250ml/crema-ducha-jazmin-250ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-250ml/crema-ducha-jazmin-250ml-2.jpg",
        tipo: "Cremas de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: true,
        cantidad: "250 ml",
        nuevo: false,
    },

    {
        id: 18,
        nombre: "Crema de Ducha Verbena Limón",
        url: "crema_de_ducha_extra_suave_verbena_limon",
        descripcion: 'La Crema de Ducha Extra Suave  de Verbena Limón de Le Petit Olivier con extractos botánicos naturales. Combina los beneficios de un gel de ducha y una crema hidratante, limpiando e hidratando la piel suavemente  mientras libera un  perfume con notas cítricas. Una crema de ducha limpia la piel como un gel de ducha convencional, pero también contiene ingredientes hidratantes.Iideal  pieles secas o sensibles.',
        imagen: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-250ml/crema-ducha-verbena-limon-250ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-250ml/crema-ducha-verbena-limon-250ml-2.jpg",
        tipo: "Cremas de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "250 ml",
        nuevo: false,
    },


    {
        id: 19,
        nombre: "Crema de Ducha Azahar",
        url: "crema_de_ducha_extra_suave_flor_de_naranjo",
        descripcion: 'La Crema de Ducha Extra Suave de Flor de Naranjo de Le Petit Olivier con extractos botánicos naturales.Combina los beneficios de un gel de ducha y una crema hidratante, limpiando e hidratando la piel suavemente  mientras libera un  perfume con notas dulces y florales. Una crema de ducha limpia la piel como un gel de ducha convencional, pero también contiene ingredientes hidratantes. Ideal pieles secas o sensibles.',
        imagen: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-500ml/crema-ducha-flor-naranjo-500ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-500ml/crema-ducha-flor-naranjo-500ml-2.jpg",
        tipo: "Cremas de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "500 ml",
        nuevo: false,
    },

    {
        id: 20,
        nombre: "Crema de Ducha Rosa",
        url: "crema_de_ducha_extra_suave_rosa",
        descripcion: 'La Crema de Ducha Extra Suave  de Rosa de Le Petit Olivier con extractos botánicos naturales.Combina los beneficios de un gel de ducha y una crema hidratante, limpiando e hidratando la piel suavemente  mientras libera un  perfume con notas cítricas.  Una crema de ducha limpia la piel como un gel de ducha convencional, pero también contiene ingredientes hidratantes. Ideal pieles secas o sensibles.',
        imagen: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-500ml/crema-ducha-rosa-500ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-500ml/crema-ducha-rosa-500ml-2.jpg",
        tipo: "Cremas de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "500 ml",
        nuevo: false,
    },

    {
        id: 21,
        nombre: "Crema de Ducha Flor de Cerezo",
        url: "crema_de_ducha_extra_suave_flor_de_cerezo",
        descripcion: 'La Crema de Ducha Extra Suave  de Flor de Cerezo de Le Petit Olivier con extractos botánicos naturales.Combina los beneficios de un gel de ducha y una crema hidratante, limpiando e hidratando la piel suavemente  mientras libera un  perfume con notas cítricas.  Una crema de ducha limpia la piel como un gel de ducha convencional, pero también contiene ingredientes hidratantes. Ideal para pieles secas o sensibles.',
        imagen: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-500ml/crema-ducha-flor-cerezo-500ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Cremas-de-Ducha-500ml/crema-ducha-flor-cerezo-500ml-2.jpg",
        tipo: "Cremas de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "500 ml",
        nuevo: false,
    },
]