export const cremasFaciales = [
    {
        id: 44,
        nombre: "Crema Hidratante Día y Noche Argán",
        url: "crema_dia_noche_argan",
        descripcion: "La Crema Día y Noche Argán para pieles maduras proporciona 24 horas de hidratación y actúa sobre los signos de la edad. Formulada con tres potentes activos -Aceite de Argán, Vitamina C* y Ácido Hialurónico-, alisa las facciones para reducir la apariencia de arrugas e ilumina el tono de piel día tras día.",
        imagen: "images/products/Cuidado-Coporal-y-Facial/Linea-Argan-Antiedad-Todo-Tipo-de-Piel/Cremas-Faciales/Crema-dia-noche-Argan-1.jpg",
        imagen2: "images/products/Cuidado-Coporal-y-Facial/Linea-Argan-Antiedad-Todo-Tipo-de-Piel/Cremas-Faciales/Crema-dia-noche-Argan-2.jpg",
        imagen3: "images/products/Cuidado-Coporal-y-Facial/Linea-Argan-Antiedad-Todo-Tipo-de-Piel/Cremas-Faciales/Crema-dia-noche-Argan-3.jpg",
        imagen4: "images/products/Cuidado-Coporal-y-Facial/Linea-Argan-Antiedad-Todo-Tipo-de-Piel/Cremas-Faciales/Crema-dia-noche-Argan-4.jpg",
        imagen5: "images/products/Cuidado-Coporal-y-Facial/Linea-Argan-Antiedad-Todo-Tipo-de-Piel/Cremas-Faciales/Crema-dia-noche-Argan-5.jpg",
        tipo: "Cremas Faciales",
        necesidad: "Cuidado Facial",
        linea: "Línea Argán",
        destacado: false,
        cantidad: "50 ml",
        nuevo: false,
    },
    {
        id: 46,
        nombre: "Crema Hidratante Facial Oliva",
        url: "crema_hidratante_dia_oliva",
        descripcion: "La Crema de Día Hidratante nutre en profundidad y proporciona una hidratación duradera para pieles normales a secas. Su fórmula sin siliconas, elaborada a base de Aceite de Oliva, deja la piel suave, calmada y con un tono radiante.",
        imagen: "images/products/Cuidado-Coporal-y-Facial/Linea-Oliva-Hidratante-Piel-Normal-a-Seca/Crema Facial/Crema-hidratante-dia-Oliva-1.jpg",
        imagen2: "images/products/Cuidado-Coporal-y-Facial/Linea-Oliva-Hidratante-Piel-Normal-a-Seca/Crema Facial/Crema-hidratante-dia-Oliva-2.jpg",
        imagen3: "images/products/Cuidado-Coporal-y-Facial/Linea-Oliva-Hidratante-Piel-Normal-a-Seca/Crema Facial/Crema-hidratante-dia-Oliva-3.jpg",
        imagen4: "images/products/Cuidado-Coporal-y-Facial/Linea-Oliva-Hidratante-Piel-Normal-a-Seca/Crema Facial/Crema-hidratante-dia-Oliva-4.jpg",
        imagen5: "images/products/Cuidado-Coporal-y-Facial/Linea-Oliva-Hidratante-Piel-Normal-a-Seca/Crema Facial/Crema-hidratante-dia-Oliva-5.jpg",
        imagen6: "images/products/Cuidado-Coporal-y-Facial/Linea-Oliva-Hidratante-Piel-Normal-a-Seca/Crema Facial/Crema-hidratante-dia-Oliva-6.jpg",
        tipo: "Cremas Faciales",
        necesidad: "Cuidado Facial",
        linea: "Línea Oliva",
        destacado: false,
        cantidad: "50 ml",
        nuevo: false,
    }
];
