export const geles = [    
    {
        id: 14,
        nombre: "Gel de Ducha al Agua de Oliva Bio - Almendra de Valensole",
        url: "gel_de_ducha_agua_de_oliva_organica_almendra",
        descripcion: 'Evádete al corazón de los campos de almendros provenzales con el Gel de Ducha al Agua de Oliva Bio Almendra de Valensole de Le Petit Olivier, para un verdadero momento de placer e hidratación bajo la ducha. Su fórmula suave, de pH neutro para la piel, ha sido testada bajo control dermatológico.',
        imagen: "images/products/Cremas-de-Ducha/Geles-de-Ducha/Geles-de-Ducha-270ml/gel-ducha-almendra-270ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Geles-de-Ducha/Geles-de-Ducha-270ml/gel-ducha-almendra-270ml-2.jpg",
        tipo: "Geles de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: true,
        cantidad: "270 ml",
        nuevo: false,
    },

    {
        id: 15,
        nombre: "Gel de Ducha al Agua de Oliva Bio - Melocotón de Manosque",
        url: "gel_de_ducha_agua_de_oliva_durazno",
        descripcion: 'Evádete al corazón de los huertos provenzales con el Gel de Ducha al Agua de Oliva Bio Melocotón de Manosque de Le Petit Olivier, para un verdadero momento de placer e hidratación bajo la ducha. Su fórmula suave, de pH neutro para la piel, limpia con suavidad mientras hidrata.',
        imagen: "images/products/Cremas-de-Ducha/Geles-de-Ducha/Geles-de-Ducha-270ml/gel-ducha-durazno-270ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Geles-de-Ducha/Geles-de-Ducha-270ml/gel-ducha-durazno-270ml-2.jpg",
        tipo: "Geles de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "270 ml",
        nuevo: false,
    },

    {
        id: 16,
        nombre: "Gel de Ducha al Agua de Oliva Bio - Lima de Córcega",
        url: "gel_de_ducha_agua_de_oliva_lima",
        descripcion: 'Este gel ducha de textura generosa y untuosa espuma, limpia la piel suavemente y libera un perfume con notas cítricas. Escápate al corazón de los limoneros de Córcega, para disfrutar de un auténtico momento de placer y frescor en la ducha. Para el extracto de este gel de ducha, Le Petit Olivier ha seleccionado limones con su pulpa pulposa y jugosa, procedentes de la llanura oriental de Puntimoso, en Córcega. Para participar en la economía circular, Le Petit Olivier sustituye parte del agua de sus geles de ducha por agua de oliva ecológica del Valle de Baux de Provenza, que habitualmente no se utiliza. Además sus envases son reciclables.',
        imagen: "images/products/Cremas-de-Ducha/Geles-de-Ducha/Geles-de-Ducha-270ml/gel-ducha-lima-270ml-1.jpg",
        imagen2: "images/products/Cremas-de-Ducha/Geles-de-Ducha/Geles-de-Ducha-270ml/gel-ducha-lima-270ml-2.jpg",
        tipo: "Geles de Ducha", 
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "270 ml",
        nuevo: false,
    },
]