export const shampoos = [
        {
        id: 22,
        nombre: "Shampoo Micelar Purificante para Cabello Graso con Aloe Vera y Té Verde",
        url: "shampoo_micelar_purificante_para_cabello_graso_con_aloe_vera_y_te_verde",
        descripcion: "Para un cabello hermoso, es fundamental elegir un shampoo adaptado a tu tipo de cabello. Le Petit Olivier ofrece un shampoo micelar suave formulado para cabello graso que reequilibra tu cabello. Con base de Aloe Vera y Extracto de Té Verde deja tu cabello limpio y brillante por más tiempo.",
        imagen: "images/products/Capilar/Linea-Cabello-Graso/shampoo-cabello-graso-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Graso/shampoo-cabello-graso-2.jpg",
        tipo: "Shampoo", 
        necesidad: "Capilar",
        linea: "Cabello Graso",
        destacado: false,
        cantidad: "250 ml",
        nuevo: false,
        beneficios: "Obtiene un cabello limpio y brillante gracias sus ingredientes:  Aloe Vera regula la secreción de sebo gracias a su acción purificadora, aporta brillo y fuerza al cabello. Extracto de Té Verde: Antioxidante, purificador y regenerador. Le Petit Olivier cuida de ti con fórmulas naturales, libres de químicos agresivos y sin disruptores endocrinos. Este producto tiene un 95% de ingredientes naturales, es vegano, libre de testeo animal, no contiene siliconas, sulfatos ni parabenos. Es Hecho en Francia.",
    },

    {
        id: 23,
        nombre: "Shampoo para Cabello Normal con Almendra Dulce y Crema de Arroz",
        url: "shampoo_para_cabello_normal_con_almendra_dulce_y_crema_de_arroz",
        descripcion: "Para un cabello hermoso, es fundamental elegir un shampoo adaptado a tu tipo de cabello.Le Petit Olivier ofrece un shampoo suave formulado para cabello normal que devuelve la fuerza y la hidratación a tu cabello. A base de almendra dulce & crema de arroz este shampoo deja tu cabello suave y brillante.",
        imagen: "images/products/Capilar/Linea-Cabello-Normal/shampoo-cabello-normal-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Normal/shampoo-cabello-normal-2.jpg",
        tipo: "Shampoo", 
        necesidad: "Capilar",
        linea: "Cabello Normal",
        destacado: false,
        cantidad: "250 ml",
        nuevo: false,
        beneficios: "Obtiene un cabello suave y brillante gracias sus ingredientes:  Almendra Dulce suaviza y protege la fibra capilar. Crema de arroz: Virtudes suavizantes y nutritivas. Le Petit Olivier cuida de ti con fórmulas naturales, libres de químicos agresivos y sin disruptores endocrinos. Este producto tiene un 95% de ingredientes naturales, es vegano, libre de testeo animal, no contiene siliconas, sulfatos ni parabenos. Es Hecho en Francia.",
    },

    {
        id: 24,
        nombre: "Shampoo para Cabello Rizado con Manteca de Karité y Aceite de Macadamia",
        url: "shampoo_para_cabello_rizado_con_manteca_de_karite_y_aceite_de_macadamia",
        descripcion: "Para un cabello hermoso, es fundamental elegir un shampoo adaptado a tu tipo de cabello.Le Petit Olivier ofrece un shampoo suave formulado para cabello rizado que hidrata y nutre  tu cabello. A base de  Mantenca de Karité y Aceite de Macadamia  este shampoo deja tus rizos definidos y fexibles.",
        imagen: "images/products/Capilar/Linea-Cabello-Rizado/shampoo-cabello-rizado-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Rizado/shampoo-cabello-rizado-2.jpg",
        tipo: "Shampoo", 
        necesidad: "Capilar",
        linea: "Cabello Rizado",
        destacado: false,
        cantidad: "250 ml",
        nuevo: false,
        beneficios: "Obtiene unos rizos definidos y flexibles  gracias sus ingredientes:  Manteca de karité: Nutritiva y protectora la manteca de karité regenera y repara la fibra capilar. Aceite de Macadamia: Protector capilar, limita las agresiones del cabello Este producto tiene un 95% de ingredientes naturales, es vegano, libre de testeo animal, no contiene siliconas, sulfatos ni parabenos. Es Hecho en Francia.",
    },
    
    {
        id: 25,
        nombre: "Shampoo para Cabello Seco y Dañado con Aceite de Oliva, Aceite de Argán y Karité",
        url: "shampoo_para_cabello_seco_y_danado_con_aceite_de_oliva_aceite_de_argan_y_karite",
        descripcion: "Para un cabello hermoso, es fundamental elegir un shampoo adaptado a tu tipo de cabello. Le Petit Olivier ofrece un shampoo reparador formulado para cabello seco y dañados para devolver la fuerza y la hidratación a tu cabello. A base de aceite de Argán, aceite de Oliva y manteca de Karité este shampoo deja tu cabello perfectamente reparado y nutrido, recuperando así su suavidad, flexibilidad y brillo natural.",
        imagen: "images/products/Capilar/Linea-Cabello-Seco-Danado/shampoo-cabello-seco-danado-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Seco-Danado/shampoo-cabello-seco-danado-2.jpg",
        tipo: "Shampoo", 
        necesidad: "Capilar",
        linea: "Cabello Seco y Dañado",
        destacado: false,
        cantidad: "250 ml",
        nuevo: false,
        beneficios: "Obtiene un cabello reparado y nutrido  gracias sus ingredientes: Aceite de Argán: Nutritivo, regenerante. Aceite de Oliva: Hidratante y nutritivo gracias a su alto contenido de vitamina E y Polifenoles. Manteca de karité: Nutritiva ,regenera y repara. Le Petit Olivier cuida de ti con fórmulas naturales, libres de químicos agresivos y sin disruptores endocrinos. Este producto tiene un 95% de ingredientes naturales, es vegano, libre de testeo animal, no contiene siliconas, sulfatos ni parabenos. Es Hecho en Francia.",
    },
]