export const acondicionadores = [
    {
        id: 26,
        nombre: "Acondicionador Micelar Purificante para Cabello Graso con Aloe Vera y Té Verde",
        url: "acondicionador_micelar_purificante_para_cabello_graso_con_aloe_vera_y_te_verde",
        descripcion: "Después del shampoo, el Acondicionador Cabello Graso es el siguiente paso en la rutina de cuidado y desenredado del cabello. Fácil de aplicar, este es el paso de belleza que marca la diferencia para tener un cabello radiante. El acondicionador micelar regulador con Aloe Vera y Extracto de Té Verde de Le Petit Olivier aclara, purifica y da brillo al cabello graso.",
        imagen: "images/products/Capilar/Linea-Cabello-Graso/acondicionador-cabello-graso-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Graso/acondicionador-cabello-graso-2.jpg",
        tipo: "Acondicionador", 
        necesidad: "Capilar",
        linea: "Cabello Graso",
        destacado: false,
        cantidad: "200 ml",
        nuevo: false,
    },

    {
        id: 27,
        nombre: "Acondicionador para Cabello Normal con Almendra Dulce y Crema de Arroz",
        url: "acondicionador_para_cabello_normal_con_almendra_dulce_y_crema_de_arroz",
        descripcion: "Después del shampoo, el Acondicionador Cabello Normal es el siguiente paso en la rutina de cuidado y desenredado del cabello. Fácil de aplicar, este es el paso de belleza que marca la diferencia para tener un cabello radiante. El acondicionador de leche de almendras dulces y crema de arroz de Le Petit Olivier desenreda, suaviza y da brillo al cabello normal.",
        imagen: "images/products/Capilar/Linea-Cabello-Normal/acondicionador-cabello-normal-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Normal/acondicionador-cabello-normal-2.jpg",
        tipo: "Acondicionador", 
        necesidad: "Capilar",
        linea: "Cabello Normal",
        destacado: false,
        cantidad: "200 ml",
        nuevo: false,
    },

    {
        id: 28,
        nombre: "Acondicionador para Cabello Rizado con Manteca de Karité y Aceite de Macadamia",
        url: "acondicionador_para_cabello_rizado_con_manteca_de_karite_y_aceite_de_macadamia",
        descripcion: "Después del shampoo, el acondicionador es el siguiente paso en la rutina de cuidado y desenredado del cabello. El Acondicionador Cabello Rizado es fácil de aplicar, este es el paso de belleza que marca la diferencia para tener un cabello radiante. El acondicionador de manteca de karité y aceite de macadamia de Le Petit Olivier desenreda, suaviza, nutre y repara el cabello con rulos.",
        imagen: "images/products/Capilar/Linea-Cabello-Rizado/acondicionador-cabello-rizado-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Rizado/acondicionador-cabello-rizado-2.jpg",
        tipo: "Acondicionador", 
        necesidad: "Capilar",
        linea: "Cabello Rizado",
        destacado: false,
        cantidad: "200 ml",
        nuevo: false,
    },

    {
        id: 29,
        nombre: "Acondicionador para Cabello Seco y Dañado con Aceite de Oliva, Aceite de Argán y Karité",
        url: "acondicionador_para_cabello_seco_y_danado_con_aceite_de_oliva_aceite_de_argan_y_karite",
        descripcion: "Después del shampoo, el acondicionador es el siguiente paso en la rutina de cuidado y desenredado del cabello. Fácil de aplicar, este es el paso de belleza que marca la diferencia para tener un cabello radiante. El acondicionador nutritivo con aceites de Oliva, Karité y Argán de Le Petit Olivier desenreda, nutre y repara el cabello seco y dañado.",
        imagen: "images/products/Capilar/Linea-Cabello-Seco-Danado/acondicionador-cabello-seco-danado-1.jpg",
        imagen2: "images/products/Capilar/Linea-Cabello-Seco-Danado/acondicionador-cabello-seco-danado-2.jpg",
        tipo: "Acondicionador", 
        necesidad: "Capilar",
        linea: "Cabello Seco y Dañado",
        destacado: false,
        cantidad: "200 ml",
        nuevo: false,
    },
]