export const jabones = [
    {
        id: 1,
        nombre: "Jabón Líquido de Marsella - Aroma Lavanda",
        url: "jabon_liquido_de_marsella_lavanda",
        descripcion: "El Puro Jabón Líquido de Marsella con aroma Lavanda se elabora según el método tradicional de cocción al caldero. Naturalmente enriquecido con glicerina, limpia las manos y el cuerpo con suavidad. Su fragancia floral y relajante te transporta directamente a los campos de la Provenza.",
        imagen: "images/products/Jabones-liquidos/jabon-liquido-lavanda-1.jpg",
        imagen2: "images/products/Jabones-liquidos/jabon-liquido-lavanda-2.jpg",
        tipo: "Jabones Líquidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: true,
        cantidad: "300ml",
        nuevo: false,
    },
    {
        id: 2,
        nombre: "Jabón Líquido de Marsella - Aroma Rosa",
        url: "jabon_liquido_marsella_rosa",
        descripcion: "El Puro Jabón Líquido de Marsella de Le Petit Olivier con aroma Rosa se elabora según el método tradicional de cocción al caldero. Naturalmente glicerinado, limpia las manos y el cuerpo con suavidad. Su fragancia a Rosa, creada en Grasse, te transporta al corazón de la Provenza.",
        imagen: "images/products/Jabones-liquidos/jabon-liquido-rosa-1.jpg",
        imagen2: "images/products/Jabones-liquidos/jabon-liquido-rosa-2.jpg", 
        tipo: "Jabones Líquidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "300ml",
        nuevo: false,
    },
    {
        id: 3,
        nombre: "Jabón Líquido de Marsella - Aroma Verbena-Limón",
        url: "jabon_liquido_de_marsella_verbena_y_limon",
        descripcion: "El Puro Jabón Líquido de Marsella con aroma Verbena-Limón se elabora según el método tradicional de cocción al caldero. Naturalmente enriquecido con glicerina, limpia las manos y el cuerpo con suavidad. Su fragancia fresca y tónica te transporta directamente a la Provenza.",
        imagen: "images/products/Jabones-liquidos/jabon-liquido-citricos-1.jpg",
        imagen2: "images/products/Jabones-liquidos/jabon-liquido-citricos-2.jpg",
        tipo: "Jabones Líquidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "300ml",
        nuevo: false,
    },
    {
        id: 4,
        nombre: "Jabón Líquido de Marsella - Aroma Flor de Naranjo",
        url: "jabon_liquido_de_marsella_flor_de_naranjo",
        descripcion: "El Puro Jabón Líquido de Marsella de Le Petit Olivier con aroma Flor de Naranjo se elabora según el método tradicional de cocción al caldero. Naturalmente enriquecido con glicerina, limpia las manos y el cuerpo con suavidad. Su fragancia floral te invita al corazón de la Provenza.",
        imagen: "images/products/Jabones-liquidos/jabon-liquido-naranja-1.jpg",
        imagen2: "",
        tipo: "Jabones Líquidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "300ml",
        nuevo: false,
    },
    {
        id: 5,
        nombre: "Jabón Extra Suave - Aroma Lavanda",
        url: "jabon_solido_extra_suave_lavanda",
        descripcion: "El jabón Extra Suave a la Lavanda limpia la piel sin agredirla y deja una fragancia emblemática del sur. Su fórmula enriquecida con Aceite de Oliva aporta suavidad y confort día a día.",
        imagen: "images/products/Jabones-solidos/250g/jabon-solido-lavanda-250g-1.jpg",
        imagen2: "images/products/Jabones-solidos/250g/jabon-solido-lavanda-250g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "250g",
        nuevo: false,
    },
    {
        id: 6,
        nombre: "Jabón Sólido Extra Suave Rosa",
        url: "jabon_solido_extra_suave_rosa",
        descripcion: "El Jabón sólido extra suave Rosa, de Le Petit Olivier está formulada en base a aceites vegetales. Enriquecida con aceite de oliva reconocido por sus destacadas propiedades hidratantes y extractos naturales que limpian suavemente la piel. Para la higiene personal el jabón sólido es una excelente alternativa. Apto para pieles sensibles.",
        imagen: "images/products/Jabones-solidos/100g/jabon-solido-rosa-100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/100g/jabon-solido-rosa-100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: true,
        cantidad: "100g",
        nuevo: false,
    },
    {
        id: 7,
        nombre: "Jabón Extra Suave Sobregraso - Aroma Aceite de Argán",
        url: "jabon_solido_extra_suave_argan",
        descripcion: "El jabón Sobregraso al Aceite de Argán limpia la piel con suavidad mientras preserva su hidratación. Su fórmula sobregrasa, enriquecida con Aceite de Oliva y Aceite de Argán, ofrece un confort inmediato, ideal para las pieles secas.",
        imagen: "images/products/Jabones-solidos/100g/jabon-solido-argan-100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/100g/jabon-solido-argan-100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "250g",
        nuevo: false,
    },
    {
        id: 8,
        nombre: "Jabón Sólido Extra Suave Verbena Limón",
        url: "jabon_solido_extra_suave_verbena_limon",
        descripcion: "El Jabón sólido extra suave Verbena Limón , de Le Petit Olivier está formulada en base a aceites vegetales. Enriquecida con aceite de oliva reconocido por sus destacadas propiedades hidratantes y extractos naturales que limpian suavemente la piel. Para la higiene personal el jabón sólido es una excelente alternativa. Apto para pieles sensibles.",
        imagen: "images/products/Jabones-solidos/100g/jabon-solido-citrico-100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/100g/jabon-solido-citrico-100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "100g",
        nuevo: false,
    },
    {
        id: 9,
        nombre: "2 Jabones Extra Suaves - Aroma Verbena-Limón",
        url: "jabon_solido_extra_suave_de_verbena_limon",
        descripcion: "Los jabones Extra Suaves están enriquecidos con Aceite de Oliva para una piel limpia con total suavidad. Su fragancia fresca y tónica de Verbena-Limón evoca un paseo por la Provenza.",
        imagen: "images/products/Jabones-solidos/2x100g/jabon-solido-citricos-2x100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/2x100g/jabon-solido-citricos-2x100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "2 x 100g",
        nuevo: false,
    },
    {
        id: 10,
        nombre: "2 Jabones Extra Suaves - Aloe Vera",
        url: "jabon_solido_extra_suave_de_aloe_vera",
        descripcion: "Los jabones Extra Suaves con Aloe Vera ofrecen una limpieza llena de frescor. Su fórmula suave, a base de ingredientes de origen natural, respeta la piel día a día. Enriquecidos con Aceite de Oliva, dejan una sensación de confort inmediato.",
        imagen: "images/products/Jabones-solidos/2x100g/jabon-solido-aloevera-2x100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/2x100g/jabon-solido-aloevera-2x100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "2 x 100g",
        nuevo: false,
    },
    {
        id: 11,
        nombre: "2 Jabones Extra Suaves - Aroma Flor de Cerezo",
        url: "jabon_solido_extra_suave_de_flor_de_cerezo",
        descripcion: "Los jabones Extra Suaves limpian la piel con suavidad y dejan una fragancia delicada y floral. Su fórmula de base vegetal, enriquecida con Aceite de Oliva, respeta el equilibrio natural de la piel. Ideales para el uso diario.",
        imagen: "images/products/Jabones-solidos/2x100g/jabon-solido-flor-cerezo-2x100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/2x100g/jabon-solido-flor-cerezo-2x100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "2 x 100g",
        nuevo: false,
    },
    {
        id: 12,
        nombre: "2 Jabones Extra Suaves - Aroma Flor de Naranjo",
        url: "jabon_solido_extra_suave_de_flor_de_naranjo",
        descripcion: "Los jabones Extra Suaves de Le Petit Olivier están enriquecidos con Aceite de Oliva y limpian la piel con total suavidad. Su fragancia floral y relajante de Flor de Naranjo invita a un momento de descanso en la Provenza.",
        imagen: "images/products/Jabones-solidos/2x100g/jabon-solido-naranja-2x100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/2x100g/jabon-solido-naranja-2x100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "2 x 100g",
        nuevo: false,
    },
    {
        id: 13,
        nombre: "2 Jabones Extra Suaves - Aroma Rosa",
        url: "jabon_solido_extra_suave_de_rosa",
        descripcion: "Los jabones Extra Suaves enriquecidos con Aceite de Oliva, te harán viajar al sur de Francia. Una espuma fina y una fragancia empolvada de Rosa para una piel limpia con total suavidad. Ideales para el uso diario.",
        imagen: "images/products/Jabones-solidos/100g/jabon-solido-rosa-100g-1.jpg",
        imagen2: "images/products/Jabones-solidos/100g/jabon-solido-rosa-100g-2.jpg",
        tipo: "Jabones Sólidos",
        necesidad: "Limpieza",
        linea: "",
        destacado: false,
        cantidad: "2 x 100g",
        nuevo: false,
    },
]